export interface FlagEntry {
  code: string;
  label: string;
}

export const FLAG_DATA: FlagEntry[] = [
  { code: 'ad', label: 'Andorra' },
  { code: 'ae', label: 'United Arab Emirates' },
  { code: 'af', label: 'Afghanistan' },
  { code: 'ag', label: 'Antigua and Barbuda' },
  { code: 'ai', label: 'Anguilla' },
  { code: 'al', label: 'Albania' },
  { code: 'am', label: 'Armenia' },
  { code: 'ao', label: 'Angola' },
  { code: 'aq', label: 'Antarctica' },
  { code: 'ar', label: 'Argentina' },
  { code: 'as', label: 'American Samoa' },
  { code: 'at', label: 'Austria' },
  { code: 'au', label: 'Australia' },
  { code: 'aw', label: 'Aruba' },
  { code: 'ax', label: 'Åland Islands' },
  { code: 'az', label: 'Azerbaijan' },
  { code: 'ba', label: 'Bosnia and Herzegovina' },
  { code: 'bb', label: 'Barbados' },
  { code: 'bd', label: 'Bangladesh' },
  { code: 'be', label: 'Belgium' },
  { code: 'bf', label: 'Burkina Faso' },
  { code: 'bg', label: 'Bulgaria' },
  { code: 'bh', label: 'Bahrain' },
  { code: 'bi', label: 'Burundi' },
  { code: 'bj', label: 'Benin' },
  { code: 'bl', label: 'Saint Barthélemy' },
  { code: 'bm', label: 'Bermuda' },
  { code: 'bn', label: 'Brunei' },
  { code: 'bo', label: 'Bolivia' },
  { code: 'bq', label: 'Caribbean Netherlands' },
  { code: 'br', label: 'Brazil' },
  { code: 'bs', label: 'Bahamas' },
  { code: 'bt', label: 'Bhutan' },
  { code: 'bv', label: 'Bouvet Island' },
  { code: 'bw', label: 'Botswana' },
  { code: 'by', label: 'Belarus' },
  { code: 'bz', label: 'Belize' },
  { code: 'ca', label: 'Canada' },
  { code: 'cc', label: 'Cocos (Keeling) Islands' },
  { code: 'cd', label: 'DR Congo' },
  { code: 'cf', label: 'Central African Republic' },
  { code: 'cg', label: 'Republic of the Congo' },
  { code: 'ch', label: 'Switzerland' },
  { code: 'ci', label: "Côte d'Ivoire" },
  { code: 'ck', label: 'Cook Islands' },
  { code: 'cl', label: 'Chile' },
  { code: 'cm', label: 'Cameroon' },
  { code: 'cn', label: 'China' },
  { code: 'co', label: 'Colombia' },
  { code: 'cr', label: 'Costa Rica' },
  { code: 'cu', label: 'Cuba' },
  { code: 'cv', label: 'Cape Verde' },
  { code: 'cw', label: 'Curaçao' },
  { code: 'cx', label: 'Christmas Island' },
  { code: 'cy', label: 'Cyprus' },
  { code: 'cz', label: 'Czech Republic' },
  { code: 'de', label: 'Germany' },
  { code: 'dj', label: 'Djibouti' },
  { code: 'dk', label: 'Denmark' },
  { code: 'dm', label: 'Dominica' },
  { code: 'do', label: 'Dominican Republic' },
  { code: 'dz', label: 'Algeria' },
  { code: 'ec', label: 'Ecuador' },
  { code: 'ee', label: 'Estonia' },
  { code: 'eg', label: 'Egypt' },
  { code: 'eh', label: 'Western Sahara' },
  { code: 'er', label: 'Eritrea' },
  { code: 'es', label: 'Spain' },
  { code: 'et', label: 'Ethiopia' },
  { code: 'eu', label: 'European Union' },
  { code: 'fi', label: 'Finland' },
  { code: 'fj', label: 'Fiji' },
  { code: 'fk', label: 'Falkland Islands' },
  { code: 'fm', label: 'Micronesia' },
  { code: 'fo', label: 'Faroe Islands' },
  { code: 'fr', label: 'France' },
  { code: 'ga', label: 'Gabon' },
  { code: 'gb', label: 'United Kingdom' },
  { code: 'gb-eng', label: 'England' },
  { code: 'gb-nir', label: 'Northern Ireland' },
  { code: 'gb-sct', label: 'Scotland' },
  { code: 'gb-wls', label: 'Wales' },
  { code: 'gd', label: 'Grenada' },
  { code: 'ge', label: 'Georgia' },
  { code: 'gf', label: 'French Guiana' },
  { code: 'gg', label: 'Guernsey' },
  { code: 'gh', label: 'Ghana' },
  { code: 'gi', label: 'Gibraltar' },
  { code: 'gl', label: 'Greenland' },
  { code: 'gm', label: 'Gambia' },
  { code: 'gn', label: 'Guinea' },
  { code: 'gp', label: 'Guadeloupe' },
  { code: 'gq', label: 'Equatorial Guinea' },
  { code: 'gr', label: 'Greece' },
  { code: 'gs', label: 'South Georgia' },
  { code: 'gt', label: 'Guatemala' },
  { code: 'gu', label: 'Guam' },
  { code: 'gw', label: 'Guinea-Bissau' },
  { code: 'gy', label: 'Guyana' },
  { code: 'hk', label: 'Hong Kong' },
  { code: 'hm', label: 'Heard Island and McDonald Islands' },
  { code: 'hn', label: 'Honduras' },
  { code: 'hr', label: 'Croatia' },
  { code: 'ht', label: 'Haiti' },
  { code: 'hu', label: 'Hungary' },
  { code: 'id', label: 'Indonesia' },
  { code: 'ie', label: 'Ireland' },
  { code: 'il', label: 'Israel' },
  { code: 'im', label: 'Isle of Man' },
  { code: 'in', label: 'India' },
  { code: 'io', label: 'British Indian Ocean Territory' },
  { code: 'iq', label: 'Iraq' },
  { code: 'ir', label: 'Iran' },
  { code: 'is', label: 'Iceland' },
  { code: 'it', label: 'Italy' },
  { code: 'je', label: 'Jersey' },
  { code: 'jm', label: 'Jamaica' },
  { code: 'jo', label: 'Jordan' },
  { code: 'jp', label: 'Japan' },
  { code: 'ke', label: 'Kenya' },
  { code: 'kg', label: 'Kyrgyzstan' },
  { code: 'kh', label: 'Cambodia' },
  { code: 'ki', label: 'Kiribati' },
  { code: 'km', label: 'Comoros' },
  { code: 'kn', label: 'Saint Kitts and Nevis' },
  { code: 'kp', label: 'North Korea' },
  { code: 'kr', label: 'South Korea' },
  { code: 'kw', label: 'Kuwait' },
  { code: 'ky', label: 'Cayman Islands' },
  { code: 'kz', label: 'Kazakhstan' },
  { code: 'la', label: 'Laos' },
  { code: 'lb', label: 'Lebanon' },
  { code: 'lc', label: 'Saint Lucia' },
  { code: 'li', label: 'Liechtenstein' },
  { code: 'lk', label: 'Sri Lanka' },
  { code: 'lr', label: 'Liberia' },
  { code: 'ls', label: 'Lesotho' },
  { code: 'lt', label: 'Lithuania' },
  { code: 'lu', label: 'Luxembourg' },
  { code: 'lv', label: 'Latvia' },
  { code: 'ly', label: 'Libya' },
  { code: 'ma', label: 'Morocco' },
  { code: 'mc', label: 'Monaco' },
  { code: 'md', label: 'Moldova' },
  { code: 'me', label: 'Montenegro' },
  { code: 'mf', label: 'Saint Martin' },
  { code: 'mg', label: 'Madagascar' },
  { code: 'mh', label: 'Marshall Islands' },
  { code: 'mk', label: 'North Macedonia' },
  { code: 'ml', label: 'Mali' },
  { code: 'mm', label: 'Myanmar' },
  { code: 'mn', label: 'Mongolia' },
  { code: 'mo', label: 'Macao' },
  { code: 'mp', label: 'Northern Mariana Islands' },
  { code: 'mq', label: 'Martinique' },
  { code: 'mr', label: 'Mauritania' },
  { code: 'ms', label: 'Montserrat' },
  { code: 'mt', label: 'Malta' },
  { code: 'mu', label: 'Mauritius' },
  { code: 'mv', label: 'Maldives' },
  { code: 'mw', label: 'Malawi' },
  { code: 'mx', label: 'Mexico' },
  { code: 'my', label: 'Malaysia' },
  { code: 'mz', label: 'Mozambique' },
  { code: 'na', label: 'Namibia' },
  { code: 'nc', label: 'New Caledonia' },
  { code: 'ne', label: 'Niger' },
  { code: 'nf', label: 'Norfolk Island' },
  { code: 'ng', label: 'Nigeria' },
  { code: 'ni', label: 'Nicaragua' },
  { code: 'nl', label: 'Netherlands' },
  { code: 'no', label: 'Norway' },
  { code: 'np', label: 'Nepal' },
  { code: 'nr', label: 'Nauru' },
  { code: 'nu', label: 'Niue' },
  { code: 'nz', label: 'New Zealand' },
  { code: 'om', label: 'Oman' },
  { code: 'pa', label: 'Panama' },
  { code: 'pe', label: 'Peru' },
  { code: 'pf', label: 'French Polynesia' },
  { code: 'pg', label: 'Papua New Guinea' },
  { code: 'ph', label: 'Philippines' },
  { code: 'pk', label: 'Pakistan' },
  { code: 'pl', label: 'Poland' },
  { code: 'pm', label: 'Saint Pierre and Miquelon' },
  { code: 'pn', label: 'Pitcairn Islands' },
  { code: 'pr', label: 'Puerto Rico' },
  { code: 'ps', label: 'Palestine' },
  { code: 'pt', label: 'Portugal' },
  { code: 'pw', label: 'Palau' },
  { code: 'py', label: 'Paraguay' },
  { code: 'qa', label: 'Qatar' },
  { code: 're', label: 'Réunion' },
  { code: 'ro', label: 'Romania' },
  { code: 'rs', label: 'Serbia' },
  { code: 'ru', label: 'Russia' },
  { code: 'rw', label: 'Rwanda' },
  { code: 'sa', label: 'Saudi Arabia' },
  { code: 'sb', label: 'Solomon Islands' },
  { code: 'sc', label: 'Seychelles' },
  { code: 'sd', label: 'Sudan' },
  { code: 'se', label: 'Sweden' },
  { code: 'sg', label: 'Singapore' },
  { code: 'sh', label: 'Saint Helena' },
  { code: 'si', label: 'Slovenia' },
  { code: 'sj', label: 'Svalbard and Jan Mayen' },
  { code: 'sk', label: 'Slovakia' },
  { code: 'sl', label: 'Sierra Leone' },
  { code: 'sm', label: 'San Marino' },
  { code: 'sn', label: 'Senegal' },
  { code: 'so', label: 'Somalia' },
  { code: 'sr', label: 'Suriname' },
  { code: 'ss', label: 'South Sudan' },
  { code: 'st', label: 'São Tomé and Príncipe' },
  { code: 'sv', label: 'El Salvador' },
  { code: 'sx', label: 'Sint Maarten' },
  { code: 'sy', label: 'Syria' },
  { code: 'sz', label: 'Eswatini' },
  { code: 'tc', label: 'Turks and Caicos Islands' },
  { code: 'td', label: 'Chad' },
  { code: 'tf', label: 'French Southern Territories' },
  { code: 'tg', label: 'Togo' },
  { code: 'th', label: 'Thailand' },
  { code: 'tj', label: 'Tajikistan' },
  { code: 'tk', label: 'Tokelau' },
  { code: 'tl', label: 'Timor-Leste' },
  { code: 'tm', label: 'Turkmenistan' },
  { code: 'tn', label: 'Tunisia' },
  { code: 'to', label: 'Tonga' },
  { code: 'tr', label: 'Turkey' },
  { code: 'tt', label: 'Trinidad and Tobago' },
  { code: 'tv', label: 'Tuvalu' },
  { code: 'tw', label: 'Taiwan' },
  { code: 'tz', label: 'Tanzania' },
  { code: 'ua', label: 'Ukraine' },
  { code: 'ug', label: 'Uganda' },
  { code: 'um', label: 'U.S. Minor Outlying Islands' },
  { code: 'us', label: 'United States' },
  { code: 'uy', label: 'Uruguay' },
  { code: 'uz', label: 'Uzbekistan' },
  { code: 'va', label: 'Vatican City' },
  { code: 'vc', label: 'Saint Vincent and the Grenadines' },
  { code: 've', label: 'Venezuela' },
  { code: 'vg', label: 'British Virgin Islands' },
  { code: 'vi', label: 'U.S. Virgin Islands' },
  { code: 'vn', label: 'Vietnam' },
  { code: 'vu', label: 'Vanuatu' },
  { code: 'wf', label: 'Wallis and Futuna' },
  { code: 'ws', label: 'Samoa' },
  { code: 'xk', label: 'Kosovo' },
  { code: 'ye', label: 'Yemen' },
  { code: 'yt', label: 'Mayotte' },
  { code: 'za', label: 'South Africa' },
  { code: 'zm', label: 'Zambia' },
  { code: 'zw', label: 'Zimbabwe' },
];

/** O(1) lookup by ISO alpha-2 code */
export const FLAG_MAP: Record<string, FlagEntry> = Object.fromEntries(
  FLAG_DATA.map((f) => [f.code, f])
);
